import Head from "next/head";
import Link from "next/link";
import { useEffect, useState, useContext } from "react";
import styles from "../styles/Home.module.css";
import { supabase } from "../utils/supabase";
import WorkoutCard from "../components/WorkoutCard";
import toast from "react-hot-toast";
import { ACTION_TYPE, Authcontext } from "../context/authContext";

export default function Home({ session }) {
  const { dispatch } = useContext(Authcontext);
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const token = localStorage.getItem("supabase.auth.token") || "";
    if (token) {
      setLoading(true);
      fetchWorkouts();
      setLoading(false);
      dispatch({
        type: ACTION_TYPE.LOGIN,
        payload: true,
      });
    }
  }, [dispatch]);

  const fetchWorkouts = async () => {
    try {
      const user = supabase.auth.user();
      setLoading(true);
      const { data, error } = await supabase
        .from("workouts")
        .select("*")
        .eq("user_id", user?.id);

      if (error) throw error;
      setData(data);
    } catch (error) {
      alert(error.message);
    }
  };

  if (loading) {
    return <div className={styles.loading}>Cargando ejericios...</div>;
  }

  const handleDelete = async (id) => {
    try {
      const user = supabase.auth.user();
      const { error } = await supabase
        .from("workouts")
        .delete()
        .eq("id", id)
        .eq("user_id", user?.id);
      fetchWorkouts();
      if (error) throw error;
      toast("Workout deleted successfully");
    } catch (error) {
      alert(error.message);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>EjerciDATE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.home}>
        {!session?.user ? (
          <div>
            <p>
              Welcome to Adrenargy. Kindly Login to your account or sign in for
              a demo
            </p>
          </div>
        ) : (
          <div>
            <p className={styles.workoutHeading}>
              Hola!! <span className={styles.email}>{session.user.email}</span>
            </p>
            {data?.length === 0 ? (
              <div className={styles.noWorkout}>
                <p>Tu no tienes ejercicios por realizar</p>
                <Link href="/create">
                  <button className={styles.button}> Crear una tarea</button>
                </Link>
              </div>
            ) : (
              <div className={styles.wrapperWorkoutHeading}>
                <p className={styles.workoutHeading}>
                  Aqui aparecen tus ejericios de hoy
                </p>
                <WorkoutCard data={data} handleDelete={handleDelete} />
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
